# Generated by Django 6.0.6 on 2026-07-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
            options={
                'db_table': 'app_users',
            },
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
            options={
                'db_table': 'carriers',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
            options={
                'db_table': 'facturas',
            },
        ),
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
            options={
                'db_table': 'garantias',
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
            options={
                'db_table': 'ingresos',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Pve',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
            options={
                'db_table': 'pves',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
            options={
                'db_table': 'reservas',
            },
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
            options={
                'db_table': 'salidas',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
            options={
                'db_table': 'sellers',
            },
        ),
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
            options={
                'db_table': 'traslados',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
            options={
                'db_table': 'warehouses',
            },
        ),
    ]
